# Generated by Django 2.2.3 on 2019-07-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_movies_rating_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('id',), 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
