# Generated by Django 2.2.3 on 2019-07-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newslink',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='news',
            name='photolink',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
