# Generated by Django 2.2.3 on 2019-07-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190707_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=1024)),
                ('titlecontent', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='NewsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagefrom', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('sentanalyze', models.IntegerField()),
                ('photolink', models.CharField(default='', max_length=1024)),
                ('newslink', models.CharField(default='', max_length=1024)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('id',),
            },
        ),
    ]
