# Generated by Django 2.2.3 on 2019-07-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_filterdata_newsnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsnew',
            options={'ordering': ('id',), 'verbose_name': 'NEWNEW', 'verbose_name_plural': 'NEWNEW'},
        ),
    ]
